---
title: "Pauta para el trabajo personal de análisis exploratorio de datos"
subtitle: 'Diplomado en análisis de datos con R para la acuicultura'
author:
 name: Dr. José A. Gallardo y Dra. María Angélica Rueda.
 affiliation: Pontificia Universidad Católica de Valparaíso
 email: <jose.gallardo@pucv.cl>
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
  word_document: default
  pdf_document:
    latex_engine: xelatex
---

<style>
#TOC {
  color: black;
  font-familiy: Calibri;
  font-size: 14px;
  border-color: #708090; 
}
body {
   color: black;
   font-familiy: Calibri;
}

pre {
  color: black;
  background-color: #F8F8FF;
}
# header {
  color: #800000;
  font-familiy: Calibri;
  background-color: #F5F5F5;
  opacity: 0.8;
  font-size: 16px;
}
</style>

## CÓDIGO DE CONDUCTA

**Durante el desarrollo del trabajo personal está permitido:**

Buscar, revisar y copiar códigos que permitan desarrollar por similitud u homología el trabajo usando todo el material del curso disponible en drive y Rstudio.cloud.

Buscar, revisar y copiar códigos que permitan permitan desarrollar por similitud u homología el trabajo desde cualquier fuente de referencia externa como tutoriales, libros, videos, foros, etc.

Solicitar o entregar ayuda a los compañeros del diplomado para resolver problemas o errores en los códigos de programación.

Solicitar o entregar ayuda a los compañeros del diplomado para proponer mejoras al trabajo.

**Durante el desarrollo del trabajo personal está prohibido:**

1.- Encargar o pagar a terceros la elaboración del trabajo para ser entregado como un trabajo propio.

2.- Copiar o utilizar el trabajo de los compañeros del diplomado para entregar como propio.

4.- Solicitar ayuda para desarrollar el trabajo a otras personas como colegas, asistentes, amigos, familiares o conocidos.

5.- Solicitar ayuda para desarrollar el trabajo de forma anónima en foros o grupos de estudio públicos o privados.

## INSTRUCCIONES GENERALES

**1)** Entregar un reporte del trabajo personal de AED en formato pdf, html o word desarrollado con Rmarkdwon. Envíe el reporte al siguiente correo <jose.gallardo@pucv.cl> antes de las **14:00 PM del sábado 06 de noviembre**. 

**2)** Trabajos no entregadas o entregadas fuera de plazo se califican con la nota mínima 1,0.

```{r setup, include=FALSE, warning=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## DESCRIPCIÓN Y CONTENIDO DEL TRABAJO

El **trabajo** corresponde a un proyecto personal de análisis exploratorio de datos de acuicultura con R.

El trabajo se puede realizar simulando datos de acuicultura, mediante el uso de datos de acuicultura propios (ej. de su trabajo o tesis), o mediante la recopilación de datos de acuicultura que sean de interes del estudiante de cualquier base de datos pública.

El trabajo estará compuesto por

**1) Proyecto Git Hub:** Control de versiones del trabajo realizado, cada día de trabajo debe quedar registrado en el proyecto git. Incluye archivo **Readme**:

**2) Proyecto Rstudio.cloud:** Incluye datos que fueron analizados en formato .xls o similar y códigos utilizados para el análisis exploratorio de datos en formato .R y/o .Rmd.

**3) Reporte:** Análisis exploratorio de datos en formato pdf, html o word.

## EVALUACIÓN DEL TRABAJO

**Parámetros para el cálculo de la nota.**

|  **Item** | **valor**      |
|:-------------|:------------------|
| **Nota máxima** | 7,0 |
| **Nota mínima** | 1,0 |
| **Nota aprobación** | 4,0 |
| **Exigencia para aprobar** | 60% |
| **Puntaje máximo** | 32 |

**Puntaje según nivel de logro alcanzado en cada componente evaluado.**

|  **Nivel de logro** | **Puntaje**      |
|:-------------|:------------------|
| **Excelente** | 4 |
| **Muy bueno** | 3 |
| **Bueno** | 2 |
| **Suficiente** | 1 |
| **Insuficiente** | 0 |

**Puntaje para cada item a evaluar**  

**Proyecto Git Hub**  
- Evidencias del uso de control de versiones en github **(4 puntos)**.    
- Archivo README en github **(4 puntos)**: Incluye título del trabajo, autor y un párrafo con la descripción del problema a resolver. Incluye además un parrafo con la descripción de las variables bajo estudio, los factores que se desean analizar y el número total de observaciones.   

**Proyecto Rstudio.cloud y reporte con análisis exploratorio de datos**  
- Describe la variación de las variables de estudio usando histogramas **(4 puntos)**.  
- Identifica si los datos están balanceados o no entre tratamientos usando tablas de frecuencia **(4 puntos)**.  
- Establece relación entre variables cuantitativas y factores usando gráficas de correlación, boxplot, interacción o de tamaño de los efectos **(4 puntos)**.  
- Identifica si existen errores, datos faltantes o valores atípicos **(4 puntos)**.  
- Resume los datos usando tablas y estadística descriptiva **(4 puntos)**.  
- Utiliza librerías **readxl**, **dplyr**, **ggplot2** para el análisis exploratorio de datos **(4 puntos)**.  

 